name: NoDropMine
version: 2.0-SNAPSHOT
main: me.keylami.nodropmine.NoDropMine
api-version: 1.17
depend: [WorldGuard]
authors: [KeylAmi]
description: Drops from block breaks go to chest
commands:
  nodropmine:
    description: View information on this plugin.
    default: true
    aliases: [ndm]
    usage: /ndm